### Welcome to Paradox-Scout Jekyll! ###
########################################
# There is a bit of configuring before you can get up and running with Paradox-Scout

### Base Site settings ###
##########################

title: Paradox Scout # site title, also used in the navbar
email: lracer53@gmail.com
description: "A First Robotics Scouting Application built by Team Paradox 2102" # site description
baseurl: "https//:www.Hamilton698Scouting.com" # the subpath of your site, e.g. /blog
url: "http//:www.testwebsite698.com" # the base hostname & protocol for your site


### Header Settings ###
#######################
# Customise to how you want
header:
    title: Team 698 # the bold, bigger main text
    accent: 2017 Scouting System # the smaller, but informative accenting text
    logo: "/images/1425580311.png" # FULL path to image in the header 150x150 works well

### Footer Settings ###
#######################
# Customise to how you want
footer:
    facebook: "https://www.facebook.com/pages/FIRST-Robotics-Team-Paradox-2102/423421971073228"
    twitter: "https://twitter.com/paradox2102"
    github: "https://github.com/paradox2102/" 


### Scouting System Settings ###
################################
# These are the most imporant settings, choose carefully

scout:
    teamkey: 698
    currentevent: azpx # the Event key for the event you want to scout, can be found on TBA
    firebase:
        rooturl: https://practice-scouting.firebaseio.com # Address of Firebase Server
        apikey: AIzaSyB5fjNcUYqS3MV2x3gdC9m7eeYa8UzPVrE # API Key of Firebase
        authdomain: practice-scouting.firebaseapp.com # Domain for Firebase to Connect to
        databaseurl: https://practice-scouting.firebaseio.com # Domain for Firebase Database to Connect to
        storagebucket: practice-scouting.appspot.com # Domain for Firebase Storage Bucket to Connect to
        messagingsenderid: 224224070119 # ID for message sender

### Other Jekyll###
###################
# You should never have to change these.
encoding: utf-8
exclude: [vendor]
